<?php

namespace ContainerE15euTB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V4GoGNPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V4GoGNP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V4GoGNP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogController::allArticles' => ['privates', '.service_locator.FIZbrbw', 'get_ServiceLocator_FIZbrbwService', true],
            'App\\Controller\\BlogController::form' => ['privates', '.service_locator.dqubTjj', 'get_ServiceLocator_DqubTjjService', true],
            'App\\Controller\\BlogController::showArticles' => ['privates', '.service_locator.Zo94Ldm', 'get_ServiceLocator_Zo94LdmService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.Oi4_xhu', 'get_ServiceLocator_Oi4XhuService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BlogController:allArticles' => ['privates', '.service_locator.FIZbrbw', 'get_ServiceLocator_FIZbrbwService', true],
            'App\\Controller\\BlogController:form' => ['privates', '.service_locator.dqubTjj', 'get_ServiceLocator_DqubTjjService', true],
            'App\\Controller\\BlogController:showArticles' => ['privates', '.service_locator.Zo94Ldm', 'get_ServiceLocator_Zo94LdmService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.Oi4_xhu', 'get_ServiceLocator_Oi4XhuService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BlogController::allArticles' => '?',
            'App\\Controller\\BlogController::form' => '?',
            'App\\Controller\\BlogController::showArticles' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BlogController:allArticles' => '?',
            'App\\Controller\\BlogController:form' => '?',
            'App\\Controller\\BlogController:showArticles' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
