<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE15euTB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE15euTB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE15euTB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE15euTB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE15euTB\App_KernelDevDebugContainer([
    'container.build_hash' => 'E15euTB',
    'container.build_id' => '01b83025',
    'container.build_time' => 1622131081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE15euTB');
